site:
  title: JBang
  url: /documentation
  #start_page: jbang-all::index.adoc

asciidoc:
  attributes:
    page-pagination: ''

content:
  sources:
    - url: ../../jbang.dev
      branches: HEAD
      start_path: docs-site
    # - url: ../../jbang
    #   branches: HEAD
    #   start_path: docs
    # - url: ../../jbang-idea
    #   branches: HEAD
    #   start_path: docs
    # - url: ../../jbang-vscode
    #   branches: HEAD
    #   start_path: docs
    # - url: ../../jbang-maven-plugin
    #   branches: HEAD
    #   start_path: docs
    - url: ../../jbang-gradle-plugin
      branches: HEAD
      start_path: docs

antora:
  extensions:
    - register: '@antora/collector-extension'

ui:
  bundle:
    url: https://github.com/jbangdev/jbang-antora-ui/releases/latest/download/ui-bundle.zip
    # Required when using cache or fetch will not update ui.
    snapshot: true
